version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    image: capralg/foodgram_backend:latest
    restart: always
    container_name: backend
    volumes:
      - static_value:app/backend/static/
      - media_value:media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: capralg/foodgram_frontend:latest
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    container_name: nginx       
    ports:
      - "80:80"
    volumes:
      - static_value:/backend/static/
      - media_value:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend
